<script>
    import { title, description } from "@stores/seo";

    title.set("Home");
    description.set("Welcome to the homepage of Healthy Food!");
</script>

<h2 class="w-full text-center mb-10 text-4xl">Welcome to Healthy Food!</h2>

<div class="text-lg tracking-wide leading-7">
    <p class="my-3">
        Healthy Food is here to help you manage your daily meals. You can use Healthy Food to keep track of foods' calories and which brand
        sells them! It is for every person who loves food! Each one of us has different food needs so Healthy Food will match all of them
        for you!
    </p>

    <p class="my-3">Healthy Food gives you a moment to take a rest and catch your breath from all the difficult shopping day we had!</p>

    <ol class="my-3">
        <li>
            <strong class="font-bold">01.</strong> Healthy Food gives you free shipping and no delivery cost in United States and Canada
        </li>
        <li><strong class="font-bold">02.</strong> Healthy Food gives you five% discount for making multiple orders</li>
        <li><strong class="font-bold">03.</strong> Healthy Food gives you free shipping in United States and Canada</li>
        <li><strong class="font-bold">04.</strong> Healthy Food allows you to select your delivery date (Sunday through Saturday)</li>
    </ol>

    <p class="my-3">
        Healthy Food has all kinds of delicious food for each household. Healthy Food will save you from eating foods that may not be
        healthy for your body. Healthy Food is specially designed to help you control your portion size. Healthy Food is here to make your
        life easier and better.
    </p>
</div>

<p class="my-3 text-sm text-gray-600">
    Text generated by <a
        class="text-indigo-400 hover:underline hover:text-indigo-800"
        href="https://app.inferkit.com/demo"
        alt="app.inferkit.com"
        target="_blank"
    >
        https://app.inferkit.com/demo
    </a> (lol).
</p>
